if(MSVC)
    set(PROJECT_WARNINGS /W4)
else()
    add_definitions(-D_GNU_SOURCE)
    set(PROJECT_WARNINGS -Wall -Wextra -Wpedantic)

    # Debug-specific flags (Sanitizers)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR NOT CMAKE_BUILD_TYPE)
        message(STATUS "Enabling Sanitizers (Debug Mode)")
        set(SAN_FLAGS -fsanitize=address,undefined -fno-omit-frame-pointer -g3)
        set(DEBUG_FLAGS -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG)
        set(PROJECT_LINKER_FLAGS ${SAN_FLAGS})
        set(PROJECT_DEBUG_COMPILE_FLAGS ${SAN_FLAGS} ${DEBUG_FLAGS})
    endif()
endif()
